config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  root to: "homes#top"
  get 'home/about' => "homes#about", as: 'about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, {presence: true, length: {maximum:200}}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

        # validates :title, presence: true
        validates :name, presence: true, length: {in: 2..20},uniqueness: true
        validates :introduction, length: {maximum: 50}

         has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  protect_from_forgery


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def new
    @books=Book.all
    @user=current_user
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      @user=current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @user=current_user
    @books=Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
   @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private
    def book_params
    params.require(:book).permit(:title, :body)
    end
    
    def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController



  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def index
    @users = User.all
    @user = current_user
  end


  def show
    @users = User.all
    @user = User.find(params[:id])
    @book = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(users_path) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
  <body>
    <header></header>
    <main>
      
      <p id="notice"></p>
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
              <h1>Editing Book</h1>
              <% if @book.errors.any? %>
              <%= @book.errors.count %>errors prohibited this obj from being saved:
              <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              <% end %>
              <div class="form-group">
                <%= form_with model: @book do |f| %>
                <h4>Title</h4>
                <%= f.text_field :title, class: "form-control" %>
              </div>
              <div class="form-group">
                <h4>Opinion</h4>
                <%= f.text_area :body, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.submit 'Update Book', class:"btn btn-success" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
    </main>
  </body>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved: 
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= render 'users/list', user: @user %>


    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    
    </div>
    </div>

app/views/books/new.html.erb
<% end %>


<%= render 'users/list', user: @user %> 


    <h2>Books</h2>
    <tbody>
    <table class="table">
      <tr>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </table>
    </tbody>

app/views/books/show.html.erb
    <%= render 'users/list', user: @user %>
       <h2>Book detail</h2>
    <table class ="table">
      <tbody>
        <tr>

          <td><%=link_to user_path(@user.id) do %>
          <%= image_tag @user.get_profile_image(100,100) %><br><%= @user.name %>
          <% end %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <td><%= link_to "Edit", edit_book_path(@book.id), method: :get %></td>
          <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>

        </tr>
      </tbody>
    </table>

  <div>
    <% if @book.user == current_user %>
    <%= link_to "削除", book_path(@book.id), method: :delete %>
    <% end %>
  </div>

app/views/homes/about.html.erb
  <head>

  </head>


  <body>
    <header></header>

    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <h1 class="px-3 mx-auto">
            Welcome to <i class="fas fa-book"></i>
            <strong>Bookers</strong>!
          </h1>
        </div>
      </div>
    </main>

    <footer></footer>

  </body>

app/views/homes/top.html.erb
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>welcome to
          <i class ="fas fa-book"></i>
          <strong>Bookers</strong>
          !!</h1>
          <p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
          <p>you can share and exchange your opinions ,
          <br> inpressions , and emotions</p>
          <p>about various books!</p>

          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
                <% else %>
                <%= link_to root_path do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              <% end %>
              </li>

              <% if user_signed_in? %>
              <li>
                <%= link_to users_path(current_user.id) do %>
                <i class="fas fa-users"></i>
                Users
                <% end %>
                <% else %>
                <%= link_to about_path do %>
                <i class="fas fa-link"></i>
                About
                <% end %>
              <% end %>
              </a>
              </li>

              <% if user_signed_in? %>
              <li>
                <%= link_to books_path(current_user.id) do %>
                <i class="fas fa-book-open"></i>
                Books
                <% end %>
                <% else %>
                <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus"></i>
                Sign up
                <% end %>
              <% end %>
              </li>

              <% if user_signed_in? %>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
                <% end %>
                <% else %>
                <%= link_to user_session_path do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
                <% end %>
              <% end %>
              </li>

            </ul>
          </div></div>
      </nav>
  </header>

  <main>

    <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: message_type %>
    <% end %>

    <%= yield %>
  </main>


   <footer>
     <div class="container mt-5">
       <div class="row">
         <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
         </div>
       </div>
      </div>
   </footer>

</body>

</html>

app/views/users/_list.html.erb
      <p id = "notice"></p>
      <div class="container px-5 px-sm-0">
        <div class="row">
          <div class="col-md-3">
            <h2>User info</h2>
            <img src="">
            <table class="table">
              <tr></tr>
              <tr>
                <th>name</th>
                <th><%= current_user.name %></th>
              </tr>
              <tr>
                <th>introduction</th>
                <th><%= current_user.introduction %></th>
              </tr>
            </table>


        <div class="row">
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h1>New book</h1>
          <%= form_with model: Book.new do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>

        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
        <% end %>
        </div>
        

app/views/users/edit.html.erb
  <head></head>

  <body>
    <header></header>
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm mx-auto">
            <h2>User info</h2>
            <% if @user.errors.any? %>
              <%= @user.errors.count %>errors prohibited this obj from being saved:
              <ul>
              <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
              </ul>
              <% end %>
            <div class="form-group">
              <label for="user_name">Name</label>
              <%= form_with model: @user do |f| %>
              <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
            </div>
            <div class="form_group">
              <label for="user_introduction">Introduction</label>
              <textarea class="form-control introduction" name="user[introduction]" id="user_introduction"></textarea>
            </div>
            <div class="form-group">
              <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </main>
  </body>

app/views/users/index.html.erb
<%= render 'list', user: @user %>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
  <table class="table">
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "show", user_path(user) %></td>
    <% end %>
      </tr>
    </tbody>
  </table>
  </div>

      </div>
      </div>

app/views/users/show.html.erb
<body>
  <main>
    <div class ="container">
    <div class="row">
    <%= render 'list', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
    <table class="table">
      <tbody>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @book.each do |book| %>
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>
    </div>

  </main>

</body>